---
# Collector tasks for Ubuntu host

- name: Install required system packages
  apt: 
    name: "{{ item }}"
    state: latest 
    update_cache: yes
    force_apt_get: yes
  loop: [ 'ca-certificates', 'curl', 'gnupg', 'lsb-release']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Save the current Ubuntu release version into a variable
  shell: lsb_release -cs
  register: ubuntu_version

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present

- name: Update apt packages
  apt:
    update_cache: "yes"
    force_apt_get: "yes"

- name: Install Docker
  apt:
    name: "docker-ce"
    state: present
    force_apt_get: "yes"
